include:
  - board: xiao_ble
    shield: sigma_left rgbled_adapter
    snippet: zmk-usb-logging
  - board: xiao_ble
    shield: sigma_right rgbled_adapter
    snippet: zmk-usb-logging
  - board: xiao_ble
    shield: settings_reset
